# nyxvamp - obsidian variant (exact match with reddish-orange strings)
# author: zoedsoupe <zoey.spessanha@zeetech.io>

inherits = "nyxvamp-radiance"

# Override specific styles for exact image match
"function" = { fg = "function_fg", modifiers = ["bold"] }
"function.builtin" = { fg = "function_builtin_fg", modifiers = ["bold"] }
"ui.match_paren" = { fg = "match_paren_fg", bg = "match_paren_bg", modifiers = ["bold"] }

# Palette overrides
[palette]
# Slightly lighter yellowish background
background = "#f0e2b3"  # Lighter yellowish background
foreground = "#000000"  # Black text
cursor_fg = "#000000"
cursor_bg = "#80FFA0"  # Lighter green cursor
cursorline = "#f0e2b3"  # Same as background for no line highlight
selection = "#E0E0D0"  # Light gray selection
line_nr = "#404040"  # Dark gray line numbers
line_nr_selected = "#000000"  # Black for selected line number

# Status line colors (lighter green bar at bottom)
status_fg = "#000000"  # Black text on status
status_bg = "#80FFA0"  # Lighter green background
status_inactive_fg = "#404040"
status_inactive_bg = "#f0e2b3"

# Menu colors
menu_fg = "#000000"
menu_bg = "#f0e2b3"
menu_sel_fg = "#f0e2b3"
menu_sel_bg = "#80FFA0"
menu_scroll_fg = "#404040"
menu_scroll_bg = "#f0e2b3"
popup_fg = "#000000"
popup_bg = "#f0e2b3"

# UI virtual
virtual_ruler_bg = "#f0e2b3"  # Same as background

# Syntax highlighting
match_paren_fg = "#80FFA0"  # Lighter green for matching parentheses
match_paren_bg = "#f0e2b3"
comment_fg = "#606060"  # Dark gray comments
string_fg = "#FF4500"  # Reddish-orange for strings
string_special_fg = "#FF4500"  # Reddish-orange for special strings
constant_fg = "#000000"  # Black constants
constant_builtin_fg = "#000000"
number_fg = "#000000"  # Black numbers
boolean_fg = "#000000"
function_fg = "#0000FF"  # Blue functions
function_builtin_fg = "#0000FF"  # Blue built-in functions
keyword_fg = "#000000"  # Black keywords
keyword_control_fg = "#000000"
operator_fg = "#000000"  # Black operators
variable_fg = "#000000"
variable_builtin_fg = "#000000"
type_fg = "#000000"  # Black types
type_builtin_fg = "#000000"
attribute_fg = "#000000"
namespace_fg = "#000000"  # Black namespaces
punctuation_fg = "#000000"
symbol_fg = "#80FFA0"  # Lighter green symbols (e.g., NOR)

# Diagnostics
error_fg = "#FF0000"  # Red errors
warning_fg = "#FFA500"  # Orange warnings
info_fg = "#0000FF"  # Blue info
hint_fg = "#00CED1"  # Dark turquoise hints

# Diff colors
diff_add_fg = "#008000"  # Dark green additions
diff_delete_fg = "#FF0000"  # Red deletions
diff_change_fg = "#FFA500"  # Orange changes

# Markup colors
markup_heading_fg = "#000000"
markup_bold_fg = "#000000"
markup_italic_fg = "#000000"
markup_link_url_fg = "#000000"
markup_link_text_fg = "#000000"
markup_quote_fg = "#606060"